### ISSUE TITLE
The operation couldn’t be completed. (OCast.OCastError error 4.)

### ISSUE THREAD

**Issue by LeDanielH** [Orange-OpenSource/OCast-iOS#80]
**Describe the bug**
I can see Ocast device in the app, but as soon as I try to connect to it and startApplication, I get the error mentioned in the title.

**Logs**

```console
Ocast:trying to connect to device with deviceId 4b2b5a77-4896-49a2-b462-0009743924a8 and applicationName remote-player-stage1
Ocast:Device OTV-24A8 in connectToDevice found
Ocast:device init for OTV-24A8 success
Ocast:trying to start application for OTV-24A8
Ocast:Unexpected error while starting the application: The operation couldn’t be completed. (OCast.OCastError error 4.).
```

**To Reproduce**

```Swift
// SUCCESS => SUCCESSFULLY FINDS THE DEVICE - CALLING THE INIT
@objc(connectToDevice:withApplicationName:)
  func connectToDevice(deviceId: String, withApplicationName applicationName: String) -> Void {
    print("Ocast:trying to connect to device with deviceId \(deviceId) and applicationName \(applicationName)")
    if let device = self.devices.first(where: { $0.upnpID == deviceId }) {
      print("Ocast:Device \(device.friendlyName) in connectToDevice found")
      self.device = device
      self.applicationName = applicationName
      self.initDevice(useOldCert: false, successCallback: startApplication)
    } else {
      print("Ocast:Device in connectToDevice not found")
      self.emitErrorEvent(error: self.CONNECT_FAILED)
    }
  }

// SUCCESS => DEVICE INIT CALLS THE `successCallback`, aka `startApplication`
func initDevice(useOldCert oldCert: Bool, successCallback: @escaping () -> Void) -> Void {
    self.device?.connect(sslConfiguration(useOldCert: oldCert), completion: { error in
      if let error = error {
        if oldCert == false {
          print("Ocast:Failed to initialize device with new cert. Trying failover to old cert...")
          self.initDevice(useOldCert: true, successCallback: successCallback)
        } else {
          print("Ocast:device init failed with \(error.localizedDescription)")
        }
      } else {
        print("Ocast:device init for \(self.device!.friendlyName) success")
        successCallback()
      }
    })
  }

// ERROR
private func startApplication() {
    if self.device != nil {
      print("Ocast:trying to start application for \(self.device!.friendlyName)")
      self.device!.startApplication(completion: { error in
        if let error = error {
          print("Ocast:Unexpected error while starting the application: \(error.localizedDescription).")
          self.emitErrorEvent(error: self.CONNECT_FAILED)
        } else {
          let deviceTransformed = self.transformDeviceForJS(device: self.device!)
          self.sendEvent(withName: self.DEVICE_CONNECTED, body: deviceTransformed)
        }
      })
    } else {
      print("Ocast:trying to start application for unavailable device")
    }
  }
```

**Expected behavior**
`enum OCastError` contains the reason, why I can't startApplication.

**Smartphone**
 - Device: IPHONE 8 simulator
 - OS: 13.3
 - OCast version: 2.0.1
 - InnopiaDriver version: 2.0.2
 - XCode 11.3

**Additional context**
+ the device and its driver
```Swift
import InnopiaDriver // version 2.0.2
// ...
deviceCenter.registerDevice(InnopiaDevice.self, forManufacturer: "Innopia")
```
+ device dump log:
```YAML
- <InnopiaDriver.InnopiaDevice: 0x7fee4bca3a30> #0
  ▿ super: OCast.ReferenceDevice
    - super: NSObject
    - applicationName: nil
    - upnpID: "4b2b5a77-4896-49a2-b462-0009743924a8"
    - host: "10.0.0.7"
    - friendlyName: "OTV-24A8"
    - modelName: "cléTV"
    - manufacturer: "Innopia"
    ▿ webSocket: OCast.WebSocket #1
      - socket: nil
      - delegateQueue: <OS_dispatch_queue_serial: org.ocast.websocket[0x600000352d80] = { xref = 5, ref = 1, sref = 1, target = com.apple.root.default-qos.overcommit[0x10ab5bf80], width = 0x1, state = 0x001ffe2000000000, in-flight = 0}> #2
        - super: OS_dispatch_queue
          - super: OS_dispatch_object
            - super: OS_object
              - super: NSObject
      - pingPongTimer: nil
      - pingPongTimerRetry: 0
      - pingPongTimerMaxRetry: 2
      - pingPongTimerTimeInterval: 5.0
      - maxPayloadSize: 4096
      ▿ delegate: Optional(<InnopiaDriver.InnopiaDevice: 0x7fee4bca3a30>)
        - some: <InnopiaDriver.InnopiaDevice: 0x7fee4bca3a30> #0
    ▿ dialService: OCast.DIALService #3
      - baseURL: "http://10.0.0.7:8008/apps/"
      - urlSession: <__NSURLSessionLocal: 0x7fee4bca4a30> #4
        - super: __NSCFURLSession
          - super: NSURLSession
            - super: NSObject
    ▿ isApplicationRunning: OCast.SynchronizedValue<Swift.Bool> #5
      - queue: <OS_dispatch_queue_concurrent: org.ocast.syncronizedvalue-1FD03B93-1901-40C0-BFC0-66C0F16CD202[0x600000352c00] = { xref = 5, ref = 1, sref = 1, target = com.apple.root.default-qos[0x10ab5bf00], width = 0xffe, state = 0x0000041000000000, in-flight = 0}> #6
        - super: OS_dispatch_queue
          - super: OS_dispatch_object
            - super: OS_object
              - super: NSObject
      - value: false
    - settingsWebSocketURL: "wss://10.0.0.7:4433/ocast"
    - connectionHandler: nil
    - disconnectionHandler: nil
    ▿ commandHandlers: OCast.SynchronizedDictionary<Swift.Int, (Swift.Result<Swift.Optional<Foundation.Data>, Swift.Error>) -> ()>
      ▿ synchronizedDictionary: OCast.SynchronizedValue<Swift.Dictionary<Swift.Int, (Swift.Result<Swift.Optional<Foundation.Data>, Swift.Error>) -> ()>> #7
        - queue: <OS_dispatch_queue_concurrent: org.ocast.syncronizedvalue-C36C708F-7575-454C-85B8-4B3211E1FE8E[0x600000352b80] = { xref = 5, ref = 1, sref = 1, target = com.apple.root.default-qos[0x10ab5bf00], width = 0xffe, state = 0x0000041000000000, in-flight = 0}> #8
          - super: OS_dispatch_queue
            - super: OS_dispatch_object
              - super: OS_object
                - super: NSObject
        - value: 0 key/value pairs
    ▿ registeredEvents: OCast.SynchronizedDictionary<Swift.String, (Foundation.Data) -> ()>
      ▿ synchronizedDictionary: OCast.SynchronizedValue<Swift.Dictionary<Swift.String, (Foundation.Data) -> ()>> #9
        - queue: <OS_dispatch_queue_concurrent: org.ocast.syncronizedvalue-D9D8B7F6-9DDD-4C16-ABE3-920DF02073E3[0x600000352b00] = { xref = 5, ref = 1, sref = 1, target = com.apple.root.default-qos[0x10ab5bf00], width = 0xffe, state = 0x0000041000000000, in-flight = 0}> #10
          - super: OS_dispatch_queue
            - super: OS_dispatch_object
              - super: OS_object
                - super: NSObject
        ▿ value: 8 key/value pairs
          ▿ (2 elements)
            - key: "playbackStatus"
            - value: (Function)
          ▿ (2 elements)
            - key: "deviceAgent"
            - value: (Function)
          ▿ (2 elements)
            - key: "nameChanged"
            - value: (Function)
          ▿ (2 elements)
            - key: "powerAlert"
            - value: (Function)
          ▿ (2 elements)
            - key: "updateStatus"
            - value: (Function)
          ▿ (2 elements)
            - key: "metadataChanged"
            - value: (Function)
          ▿ (2 elements)
            - key: "deviceInfo"
            - value: (Function)
          ▿ (2 elements)
            - key: "wifiConnectionStatus"
            - value: (Function)
    - deviceUUID: "703AF697-4A67-4FFF-A617-40FC5CEEEA2A"
    - sequenceID: 0
    - sequenceQueue: <OS_dispatch_queue_serial: org.ocast.sequencequeue[0x600000353e00] = { xref = 5, ref = 1, sref = 1, target = com.apple.root.default-qos.overcommit[0x10ab5bf80], width = 0x1, state = 0x001ffe2000000000, in-flight = 0}> #11
      - super: OS_dispatch_queue
        - super: OS_dispatch_object
          - super: OS_object
            - super: NSObject
    - semaphoreQueue: <OS_dispatch_queue_serial: org.ocast.semaphorequeue[0x600000353f00] = { xref = 5, ref = 1, sref = 1, target = com.apple.root.default-qos.overcommit[0x10ab5bf80], width = 0x1, state = 0x001ffe2000000000, in-flight = 0}> #12
      - super: OS_dispatch_queue
        - super: OS_dispatch_object
          - super: OS_object
            - super: NSObject
    - semaphore: nil
    - connectionEventTimeout: 60.0
    - state: OCast.DeviceState
```
